remove bp

diff --git a/.github/actions/linter_tests/action.yaml b/.github/actions/linter_tests/action.yaml
--- a/.github/actions/linter_tests/action.yaml
+++ b/.github/actions/linter_tests/action.yaml
@@ -39,42 +39,36 @@ runs:
     # NOTE: tzdata is a dependency of php, but without the DEBIAN_FRONTEND=noninteractive
     #       it will prompt for a timezone selection
     - name: Install packages and specify defaults
-      uses: trunk-io/breakpoint@v1.3.0
-      with:
-        breakpoint-id: trunk-plugins-linter-tests
-        shell: bash
-        working-directory: ${{ inputs.path }}
-        trunk-token: ${{ inputs.trunk-token  }}
-        org: trunk-staging-org
-        run: |
-          echo "CLI_PATH=${{ inputs.cli-path }}" >> "$GITHUB_ENV"
+      run: |
+        echo "CLI_PATH=${{ inputs.cli-path }}" >> "$GITHUB_ENV"
 
-          case "$RUNNER_OS" in
-            Linux)
-              # Cleanup any existing apt locks
-              sudo killall apt-get || true
-              sudo rm /var/lib/apt/lists/lock || true
+        case "$RUNNER_OS" in
+          Linux)
+            # Cleanup any existing apt locks
+            sudo killall apt-get || true
+            sudo rm /var/lib/apt/lists/lock || true
 
-              # Install non-hermetic linters
-              sudo apt-get update
-              sudo apt-get -y install libperl-critic-perl perltidy zlib1g-dev
-              DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata
-              sudo add-apt-repository ppa:ondrej/php
-              sudo apt install -y php8.0-fpm php8.0-xml php8.0-mbstring php8.0-curl
-              ;;
-            macOS)
-              brew install cpm
-              cpm install -g --no-test --color Perl::Critic Perl::Tidy
-              brew unlink perl && brew link perl
-              brew install php gnupg
-              ;;
-            Windows)
-              echo "PLATFORM_APPEND_ARGS=--maxWorkers=5" >> "$GITHUB_ENV"
-              if [[ "${{ inputs.cli-path }}" == "" ]]; then
-                echo "CLI_PATH=${{ github.workspace }}\trunk.ps1" >> "$GITHUB_ENV"
-              fi
-              ;;
-          esac
+            # Install non-hermetic linters
+            sudo apt-get update
+            sudo apt-get -y install libperl-critic-perl perltidy zlib1g-dev
+            DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata
+            sudo add-apt-repository ppa:ondrej/php
+            sudo apt install -y php8.0-fpm php8.0-xml php8.0-mbstring php8.0-curl
+            ;;
+          macOS)
+            brew install cpm
+            cpm install -g --no-test --color Perl::Critic Perl::Tidy
+            brew unlink perl && brew link perl
+            brew install php gnupg
+            ;;
+          Windows)
+            echo "PLATFORM_APPEND_ARGS=--maxWorkers=5" >> "$GITHUB_ENV"
+            if [[ "${{ inputs.cli-path }}" == "" ]]; then
+              echo "CLI_PATH=${{ github.workspace }}\trunk.ps1" >> "$GITHUB_ENV"
+            fi
+            ;;
+        esac
+      shell: bash
 
     - name: Install dependencies
       run: npm ci
