try taking lock by force

diff --git a/.github/actions/linter_tests/action.yaml b/.github/actions/linter_tests/action.yaml
--- a/.github/actions/linter_tests/action.yaml
+++ b/.github/actions/linter_tests/action.yaml
@@ -51,14 +51,16 @@ runs:
 
           case "$RUNNER_OS" in
             Linux)
-              echo "start"
+              # Cleanup any existing apt locks
+              sudo killall apt-get || true
+              sudo rm /var/lib/apt/lists/lock || true
+
+              # Install non-hermetic linters
               sudo apt-get update
-              echo "post update"
+              sudo apt-get -y install libperl-critic-perl perltidy zlib1g-dev
+              DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install tzdata
               sudo add-apt-repository ppa:ondrej/php
-              echo "post add repository"
-              DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get -y install libperl-critic-perl perltidy zlib1g-dev \
-                tzdata php8.0-fpm php8.0-xml php8.0-mbstring php8.0-curl
-              echo "done"
+              sudo apt install -y php8.0-fpm php8.0-xml php8.0-mbstring php8.0-curl
               ;;
             macOS)
               brew install cpm
