Upload Windows nightly results (#554)
Accomplishes the following:
- Uses `ubuntu-x64` for nightly runs and repo tests
- Runs full suite on `windows-latest` for nightly
- Gates linter tests passing on Windows for upload to LUV
- Sends Slack notifications for failures on Windows nightlies
- Reports which platforms failed for better UX in notifs

Successful [nightly
run](https://github.com/trunk-io/plugins/actions/runs/6820061981)

diff --git a/.github/workflows/nightly.yaml b/.github/workflows/nightly.yaml
--- a/.github/workflows/nightly.yaml
+++ b/.github/workflows/nightly.yaml
@@ -8,7 +8,20 @@ on:
   #   paths: [.github/workflows/nightly.yaml]
   workflow_dispatch: {}
 
-permissions: read-all
+permissions:
+  actions: write
+  checks: write
+  contents: read
+  deployments: read
+  id-token: write
+  issues: write
+  discussions: read
+  packages: read
+  pages: read
+  pull-requests: write
+  repository-projects: read
+  security-events: read
+  statuses: write
 
 jobs:
   # Run tests against all linters for snapshots and latest version as they exist on main
@@ -21,12 +34,14 @@ jobs:
       fail-fast: false
       matrix:
         linter-version: [Snapshots, Latest]
-        os: [ubuntu-latest, macos-latest]
+        os: [ubuntu-x64, macos-latest, windows-latest]
     steps:
       - name: Checkout
         uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
 
       - name: Cache tool downloads
+        # ubuntu runner has persistent cache
+        if: matrix.os != 'ubuntu-x64'
         uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
         with:
           path: /tmp/plugins_testing_download_cache
@@ -63,7 +78,15 @@ jobs:
       fail-fast: false
       matrix:
         linter-version: [Snapshots, Latest]
-        os: [ubuntu-latest, macos-latest]
+        os: [ubuntu-x64, macos-latest, windows-latest]
+        include:
+          # Normalize the filenames as inputs for ease of parsing
+          - os: ubuntu-x64
+            results-file: ubuntu-latest
+          - os: macos-latest
+            results-file: macos-latest
+          - os: windows-latest
+            results-file: windows-latest
     outputs:
       plugin-version: ${{ steps.get-release.outputs.tag }}
 
@@ -76,6 +99,7 @@ jobs:
       # This assumes that any changes on main since the last release are backwards compatible
       # in terms of allowing existing linter tests to run.
       - name: Preserve test runner latest behavior
+        shell: bash
         run: |
           cp -r tests tests.bak
           cp package.json package.json.bak
@@ -108,6 +132,7 @@ jobs:
             tools
 
       - name: Overwrite test runners with latest behavior
+        shell: bash
         run: |
           rm -rf tests
           mv tests.bak tests
@@ -125,6 +150,8 @@ jobs:
         continue-on-error: true
 
       - name: Cache tool downloads
+        # ubuntu runner has persistent cache
+        if: matrix.os != 'ubuntu-x64'
         uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
         with:
           path: /tmp/plugins_testing_download_cache
@@ -144,21 +171,13 @@ jobs:
           fi
         shell: bash
 
-      - name: Linter Tests
+      - name: Linter Tests ${{ matrix.os }}
         # Use overwritten dependency action, rather than released version
         uses: ./.github/actions/linter_tests
         with:
           linter-version: ${{ matrix.linter-version }}
-          append-args: linters -- --json --outputFile=${{ matrix.os }}-res.json
+          append-args: linters -- --json --outputFile=${{ matrix.results-file }}-res.json
           sourcery-token: ${{ secrets.TRUNK_SOURCERY_TOKEN }}
-          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
-
-      # TODO(lauri): For now this just runs on the hardcoded versions. We should configure this
-      # akin to the linter_tests job.
-      - name: Tool Tests
-        if: failure() || success()
-        uses: ./.github/actions/tool_tests
-        with:
           trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
 
       - name: Upload Test Outputs for Upload Job
@@ -166,13 +185,13 @@ jobs:
         if: (failure() || success()) && matrix.linter-version == 'Latest'
         uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
         with:
-          name: ${{ matrix.os }}-test-results
-          path: ${{ matrix.os }}-res.json
+          name: ${{ matrix.results-file }}-test-results
+          path: ${{ matrix.results-file }}-res.json
 
   upload_test_results:
     name: Upload Test Results
     needs: linter_tests_release
-    runs-on: ubuntu-latest
+    runs-on: ubuntu-x64
     # Still run on test failure
     if: always()
     timeout-minutes: 10
@@ -183,30 +202,80 @@ jobs:
         uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
 
       - name: Retrieve Test Outputs ubuntu
+        id: download-ubuntu
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
+        continue-on-error: true
         with:
           name: ubuntu-latest-test-results
 
       - name: Retrieve Test Outputs macOS
+        id: download-macos
         uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
+        continue-on-error: true
         with:
           name: macos-latest-test-results
+
+      - name: Retrieve Test Outputs Windows
+        id: download-windows
+        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
+        continue-on-error: true
+        with:
+          name: windows-latest-test-results
+
+      - name: Print Test Outputs
+        continue-on-error: true
+        shell: bash
+        run: |
+          echo "::group::Ubuntu results"
+          cat "ubuntu-latest-res.json" || echo "missing"
+          echo "::endgroup::"
+
+          echo "::group::Macos results"
+          cat "macos-latest-res.json" || echo "missing"
+          echo "::endgroup::"
+
+          echo "::group::Windows results"
+          cat "windows-latest-res.json" || echo "missing"
+          echo "::endgroup::"
+
+      - name: Slack Notification For Missing Artifacts
+        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
+        if:
+          steps.download-ubuntu.outcome == 'failure' || steps.download-macos.outcome == 'failure' ||
+          steps.download-windows.outcome == 'failure'
+        with:
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
+          payload: |
+            {
+              "text": "Artifact Download Failure",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Unable to download some test result artifacts (ubuntu: ${{ steps.download-ubuntu.outcome }}, macos: ${{ steps.download-macos.outcome }}, windows: ${{ steps.download-windows.outcome }}) >"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
 
       - name: Setup Node
         uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3.8.2
         with:
           node-version: 18
 
-      - name: Sync lfs
-        run: git lfs pull
-
       - name: Install Dependencies
+        shell: bash
         run: npm ci
 
       - name: Add npm bin to path
+        shell: bash
         run: echo "$PWD/node_modules/.bin" >> "$GITHUB_PATH"
 
       - name: Parse Test Results
+        shell: bash
         id: parse
         run: |
           npm run parse
@@ -227,6 +296,7 @@ jobs:
         # upload-linter-versions is a hidden command reserved exclusively for uploading
         # validated results from the plugins repo.
         # daemon must be restarted in order to propagate environment variable
+        shell: bash
         run: |
           trunk daemon shutdown
           trunk upload-linter-versions --token="$TRUNK_API_TOKEN" results.json
@@ -240,6 +310,7 @@ jobs:
         # upload-linter-versions is a hidden command reserved exclusively for uploading
         # validated results from the plugins repo.
         # daemon must be restarted in order to propagate environment variable
+        shell: bash
         run: |
           trunk daemon shutdown
           trunk upload-linter-versions --token="$TRUNK_API_TOKEN" results.json
@@ -295,6 +366,26 @@ jobs:
             }
         env:
           SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
+
+  # Run tool tests only on main
+  tool_tests_main:
+    name: Tool Tests Main
+    runs-on: ${{ matrix.os }}
+    timeout-minutes: 120
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-x64, macos-latest, windows-latest]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
+
+      # TODO(lauri): For now this just runs on the hardcoded versions. We should configure this
+      # akin to the linter_tests job.
+      - name: Tool Tests ${{ matrix.os }}
+        uses: ./.github/actions/tool_tests
+        with:
+          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
 
   # Run repo healthcheck tests
   repo_tests:
