Improve test hygiene and parallelize tool tests (#432)
A number of fixes/improvements:
1. Tool tests were running twice on PRs needlessly
2. Extract tool tests into their own jobs. This could run into some
unfortunate "throttling" in the case of multiple PRs at once, but it
should be better for the general case
3. Add ci-debugger to the tool tests invocations on non-Windows
4. Use more sane timeouts
5. Some better logging
6. Makes some tests run on Windows and mark others to skip Windows

[Successful run
Windows](https://github.com/trunk-io/plugins/actions/runs/5836160966/job/15829177813)

diff --git a/.github/workflows/pr.yaml b/.github/workflows/pr.yaml
--- a/.github/workflows/pr.yaml
+++ b/.github/workflows/pr.yaml
@@ -83,16 +83,13 @@ jobs:
 
   # Run tests against all linters for known_good_version and latest version
   linter_tests:
-    name: Plugin Tests
+    name: Linter Tests
     runs-on: ${{ matrix.os }}
     needs: detect_changes
-    permissions:
-      pull-requests: write
     if:
       needs.detect_changes.outputs.linters == 'true' || needs.detect_changes.outputs.all-linters ==
-      'linters' || needs.detect_changes.outputs.tools == 'true' ||
-      needs.detect_changes.outputs.all-tools == 'tools'
-    timeout-minutes: 120
+      'linters'
+    timeout-minutes: 90
     strategy:
       fail-fast: false
       matrix:
@@ -131,12 +128,35 @@ jobs:
         with:
           linter-version: Latest
           sourcery-token: ${{ secrets.TRUNK_SOURCERY_TOKEN }}
-          # TODO(Tyler): We need downloads to work with known_bad_versions
           append-args: ${{ needs.detect_changes.outputs.linters-files }}
           trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
 
+  tool_tests:
+    name: Tool Tests
+    runs-on: ${{ matrix.os }}
+    needs: detect_changes
+    if:
+      needs.detect_changes.outputs.tools == 'true' || needs.detect_changes.outputs.all-tools ==
+      'tools'
+    timeout-minutes: 60
+    strategy:
+      fail-fast: false
+      matrix:
+        os: [ubuntu-latest, macos-latest]
+    steps:
+      - name: Checkout
+        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
+
+      - name: Cache tool downloads
+        uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
+        with:
+          path: /tmp/plugins_testing_download_cache
+          # No need to key on trunk version unless we change how we store downloads.
+          key: trunk-${{ runner.os }}
+
       - name: Tool Tests
         # Run tests using KnownGoodVersion with any modified tools and conditionally all tools. Don't run when cancelled.
+        # TODO(Tyler): Wire up Latest tests and ReleaseVersionService
         uses: ./.github/actions/tool_tests
         if:
           (failure() || success()) && needs.detect_changes.outputs.tools == 'true' ||
@@ -145,15 +165,7 @@ jobs:
           append-args:
             ${{ needs.detect_changes.outputs.all-tools }} ${{
             needs.detect_changes.outputs.tools-files }}
-
-      - name: Tool Tests Latest
-        # Run tests using Latest with any modified tools (see filters.yaml). Don't run when cancelled.
-        if:
-          (failure() || success()) && needs.detect_changes.outputs.tools == 'true' &&
-          needs.detect_changes.outputs.tools-files != ''
-        uses: ./.github/actions/tool_tests
-        with:
-          append-args: ${{ needs.detect_changes.outputs.tools-files }}
+          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
 
   # Run repo healthcheck tests
   repo_tests:
@@ -166,13 +178,17 @@ jobs:
     if: ${{ always() }}
     runs-on: ubuntu-latest
     name: Aggregate Test Results
-    needs: [linter_tests, repo_tests]
+    needs: [linter_tests, tool_tests, repo_tests]
     steps:
       - run: |
           linters="${{ needs.linter_tests.result }}"
           repos="${{ needs.repo_tests.result }}"
+          tools="${{ needs.tool_tests.result }}"
           if [[ $linters != "success" && $linters != "skipped" ]]; then
             echo "Detected failure in linter tests"
+            exit 1
+          elif [[ $tools != "success" && $tools != "skipped" ]]; then
+            echo "Detected failure in tool tests"
             exit 1
           elif [[ $repos != "success" && $repos != "skipped" ]]; then
             echo "Detected failure in repo tests"
