disable windows jobs

diff --git a/.github/workflows/upload_results.reusable.yaml b/.github/workflows/upload_results.reusable.yaml
--- a/.github/workflows/upload_results.reusable.yaml
+++ b/.github/workflows/upload_results.reusable.yaml
@@ -76,12 +76,13 @@ jobs:
         with:
           name: ${{ inputs.results-prefix }}macos-latest-test-results
 
-      - name: Retrieve Test Outputs Windows
-        id: download-windows
-        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
-        continue-on-error: true
-        with:
-          name: ${{ inputs.results-prefix }}windows-latest-test-results
+      # TODO(Tyler): Re-add Windows runners.
+      # - name: Retrieve Test Outputs Windows
+      #   id: download-windows
+      #   uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8
+      #   continue-on-error: true
+      #   with:
+      #     name: ${{ inputs.results-prefix }}windows-latest-test-results
 
       - name: Print Test Outputs
         continue-on-error: true
@@ -95,15 +96,15 @@ jobs:
           cat "macos-latest-res.json" || echo "missing"
           echo "::endgroup::"
 
-          echo "::group::Windows results"
-          cat "windows-latest-res.json" || echo "missing"
-          echo "::endgroup::"
+          # echo "::group::Windows results"
+          # cat "windows-latest-res.json" || echo "missing"
+          # echo "::endgroup::"
 
       - name: Slack Notification For Missing Artifacts
         uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
         if:
-          steps.download-ubuntu.outcome == 'failure' || steps.download-macos.outcome == 'failure' ||
-          steps.download-windows.outcome == 'failure'
+          steps.download-ubuntu.outcome == 'failure' || steps.download-macos.outcome == 'failure'
+          # || steps.download-windows.outcome == 'failure'
         with:
           method: chat.postMessage
           token: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
@@ -114,7 +115,7 @@ jobs:
               - type: section
                 text:
                   type: mrkdwn
-                  text: "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Unable to download some ${{ inputs.results-prefix }}test result artifacts (ubuntu: ${{ steps.download-ubuntu.outcome }}, macos: ${{ steps.download-macos.outcome }}, windows: ${{ steps.download-windows.outcome }}) >"
+                  text: "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Unable to download some ${{ inputs.results-prefix }}test result artifacts (ubuntu: ${{ steps.download-ubuntu.outcome }}, macos: ${{ steps.download-macos.outcome }} >"
 
       - name: Setup Node
         uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
