lots of chnages

diff --git a/.github/workflows/upload_results.reusable.yaml b/.github/workflows/upload_results.reusable.yaml
--- a/.github/workflows/upload_results.reusable.yaml
+++ b/.github/workflows/upload_results.reusable.yaml
@@ -34,13 +34,9 @@ on:
         required: false
       TRUNK_OPEN_PR_APP_PRIVATE_KEY:
         required: false
-      TRUNK_SNYK_TOKEN:
-        required: false
       TRUNK_SOURCERY_TOKEN:
         required: false
       TRUNK_DEBUGGER_TOKEN:
-        required: false
-      TRUNK_ORG_PROD_TOKEN:
         required: false
 
 permissions:
@@ -64,25 +60,24 @@ jobs:
 
       - name: Retrieve Test Outputs ubuntu
         id: download-ubuntu
-        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         continue-on-error: true
         with:
           name: ${{ inputs.results-prefix }}ubuntu-latest-test-results
 
       - name: Retrieve Test Outputs macOS
         id: download-macos
-        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
+        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
         continue-on-error: true
         with:
           name: ${{ inputs.results-prefix }}macos-latest-test-results
 
-      # TODO(Tyler): Re-add Windows runners.
-      # - name: Retrieve Test Outputs Windows
-      #   id: download-windows
-      #   uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
-      #   continue-on-error: true
-      #   with:
-      #     name: ${{ inputs.results-prefix }}windows-latest-test-results
+      - name: Retrieve Test Outputs Windows
+        id: download-windows
+        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4.1.7
+        continue-on-error: true
+        with:
+          name: ${{ inputs.results-prefix }}windows-latest-test-results
 
       - name: Print Test Outputs
         continue-on-error: true
@@ -96,29 +91,35 @@ jobs:
           cat "macos-latest-res.json" || echo "missing"
           echo "::endgroup::"
 
-          # echo "::group::Windows results"
-          # cat "windows-latest-res.json" || echo "missing"
-          # echo "::endgroup::"
+          echo "::group::Windows results"
+          cat "windows-latest-res.json" || echo "missing"
+          echo "::endgroup::"
 
       - name: Slack Notification For Missing Artifacts
-        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         if:
-          steps.download-ubuntu.outcome == 'failure' || steps.download-macos.outcome == 'failure'
-          # || steps.download-windows.outcome == 'failure'
+          steps.download-ubuntu.outcome == 'failure' || steps.download-macos.outcome == 'failure' ||
+          steps.download-windows.outcome == 'failure'
         with:
-          method: chat.postMessage
-          token: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
           payload: |
-            channel: ${{ env.SLACK_CHANNEL_ID }}
-            text: "Artifact Download Failure"
-            blocks:
-              - type: section
-                text:
-                  type: mrkdwn
-                  text: "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Unable to download some ${{ inputs.results-prefix }}test result artifacts (ubuntu: ${{ steps.download-ubuntu.outcome }}, macos: ${{ steps.download-macos.outcome }})>"
+            {
+              "text": "Artifact Download Failure",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Unable to download some ${{ inputs.results-prefix }}test result artifacts (ubuntu: ${{ steps.download-ubuntu.outcome }}, macos: ${{ steps.download-macos.outcome }}, windows: ${{ steps.download-windows.outcome }}) >"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
 
       - name: Setup Node
-        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
+        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
         with:
           node-version: 18
 
@@ -136,9 +137,8 @@ jobs:
         id: parse
         run: |
           npm run parse
-          echo "failures=$([[ -f failures.yaml ]] && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"
-          failures_payload=$(cat failures.yaml)
-          printf "failures-payload<<EOF\n%s\nEOF\n" "$failures_payload" >> "$GITHUB_OUTPUT"
+          echo "failures=$([[ -f failures.json ]] && echo "true" || echo "false")" >> "$GITHUB_OUTPUT"
+          echo "failures-payload=$(cat failures.json)" >> "$GITHUB_OUTPUT"
           echo "reruns=$(cat reruns.txt)" >> "$GITHUB_OUTPUT"
         env:
           PLUGIN_VERSION: ${{ inputs.plugin-version }}
@@ -146,7 +146,6 @@ jobs:
           RUN_ID: ${{ github.run_id }}
           TEST_REF: ${{ inputs.test-ref }}
           TEST_TYPE: ${{ inputs.test-type }}
-          SLACK_CHANNEL_ID: ${{ env.SLACK_CHANNEL_ID }}
 
       - name: Upload Test Results Staging
         if: inputs.upload-validated-versions == true
@@ -180,42 +179,55 @@ jobs:
 
       # Slack notifications
       - name: Slack Notification For Failures
-        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         if: always() && steps.parse.outputs.failures == 'true'
         with:
-          method: chat.postMessage
-          token: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
           payload: ${{ steps.parse.outputs.failures-payload }}
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
 
       - name: Slack Notification For Staging Upload Failure
-        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         if: inputs.upload-validated-versions == true && steps.upload-staging.outcome == 'failure'
         with:
-          method: chat.postMessage
-          token: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
           payload: |
-            channel: ${{ env.SLACK_CHANNEL_ID }}
-            text: "Upload Failure"
-            blocks:
-              - type: section
-                text:
-                  type: mrkdwn
-                  text: "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Upload Test Results to Staging >"
+            {
+              "text": "Upload Failure",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Upload Test Results to Staging >"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
 
       - name: Slack Notification For Prod Upload Failure
-        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
+        uses: slackapi/slack-github-action@70cd7be8e40a46e8b0eced40b0de447bdb42f68e # v1.26.0
         if: inputs.upload-validated-versions == true && steps.upload-prod.outcome == 'failure'
         with:
-          method: chat.postMessage
-          token: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
+          channel-id: ${{ env.SLACK_CHANNEL_ID }}
           payload: |
-            channel: ${{ env.SLACK_CHANNEL_ID }}
-            text: "Upload Failure"
-            blocks:
-              - type: section
-                text:
-                  type: mrkdwn
-                  text: "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Upload Test Results to Prod >"
+            {
+              "text": "Upload Failure",
+              "blocks": [
+                {
+                  "type": "section",
+                  "text": {
+                    "type": "mrkdwn",
+                    "text": "Failure: <https://github.com/trunk-io/plugins/actions/runs/${{ github.run_id }}| Upload Test Results to Prod >"
+                  }
+                }
+              ]
+            }
+        env:
+          SLACK_BOT_TOKEN: ${{ secrets.TRUNKBOT_SLACK_BOT_TOKEN }}
   generate_snapshots_pr:
     name: Generate Snapshots PR
     runs-on: ubuntu-latest
@@ -227,7 +239,7 @@ jobs:
         uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
 
       - name: Setup Node
-        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
+        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
         with:
           node-version: 18
 
@@ -245,10 +257,8 @@ jobs:
           linter-version: Latest
           ref-type: main
           append-args: ${{ needs.upload_test_results.outputs.reruns }} -- -u
-          snyk-token: ${{ secrets.TRUNK_SNYK_TOKEN }}
           sourcery-token: ${{ secrets.TRUNK_SOURCERY_TOKEN }}
-          trunk-staging-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
-          trunk-prod-token: ${{ secrets.TRUNK_ORG_PROD_TOKEN }}
+          trunk-token: ${{ secrets.TRUNK_DEBUGGER_TOKEN }}
         env:
           PLUGINS_TEST_UPDATE_SNAPSHOTS: "true"
 
@@ -265,7 +275,7 @@ jobs:
           private_key: ${{ secrets.TRUNK_OPEN_PR_APP_PRIVATE_KEY }}
 
       - name: Create Pull Request
-        uses: peter-evans/create-pull-request@v7
+        uses: peter-evans/create-pull-request@v6
         with:
           title: Auto-add missing snapshots
           body:
