revert to old install

diff --git a/.github/actions/tool_tests/action.yaml b/.github/actions/tool_tests/action.yaml
--- a/.github/actions/tool_tests/action.yaml
+++ b/.github/actions/tool_tests/action.yaml
@@ -29,18 +29,23 @@ runs:
       with:
         node-version: 18
 
-    - name: Setup PHP
-      uses: shivammathur/setup-php@v2
-      with:
-        php-version: "8.2"
-        extensions: none, mbstring, curl, xml, dom
-        tools: none
-
-    - name: Specify defaults
+    - name: Install packages and specify defaults
       run: |
         echo "CLI_PATH=${{ inputs.cli-path }}" >> "$GITHUB_ENV"
 
         case "$RUNNER_OS" in
+          Linux)
+            # Cleanup any existing apt locks
+            sudo killall apt-get || true
+            sudo rm /var/lib/apt/lists/lock || true
+
+            sudo add-apt-repository ppa:ondrej/php
+            sudo apt-get update
+            sudo apt install -y php8.2-fpm php8.2-xml php8.2-mbstring php8.2-curl
+            ;;
+          macOS)
+            brew install php gnupg
+            ;;
           Windows)
             echo "PLATFORM_APPEND_ARGS=--maxWorkers=5" >> "$GITHUB_ENV"
             if [[ "${{ inputs.cli-path }}" == "" ]]; then
